#pragma once

#include "ui/IMountHost.h"

namespace dearoreui::ui {

// Stage 7 default mount host: the actual DOM container creation is performed by
// the JavaScript bootstrap script generated by RuntimeInjector. C++ side only
// tracks lifecycle state and defers DOM operations to the trusted runtime script.
class NullMountHost : public IMountHost {
public:
    [[nodiscard]] api::Result<void>
    createContainer(api::ContextId /*contextId*/, OverlaySpec const& /*spec*/) override {
        return api::Result<void>::success();
    }

    [[nodiscard]] api::Result<void>
    removeContainer(api::ContextId /*contextId*/, std::string_view /*containerId*/) override {
        return api::Result<void>::success();
    }

    [[nodiscard]] bool isAvailable() const override { return true; }
};

} // namespace dearoreui::ui
